### ISSUE TITLE
请问是否能添加声音渐入的支持？

### ISSUE THREAD

**Issue by JedSunCN** [lingkai5wu/AutoMuteBG#1]
在切换回星穹铁道时，有时候切回去正好碰到打击音效（有点辣耳朵），请问是否有意向添加切回声音渐强功能？

**Comment by JedSunCN** [comment]
#2

**Comment by JedSunCN** [comment]
尝试简单地改了下代码🤣

**Comment by lingkai5wu** [comment]
首先感谢你的建议和贡献，我目前设想的实现方案和你的一致，不过考虑到程序的健壮性，还需要注意以下问题：

1. 若短时间内两次切入程序（短于淡入完成），可能出现音量忽大忽小。
2. 尚未评估`SimpleAudioVolume.SetMasterVolume`方法的开销，待评估后再确定建议的可行性及调整的粒度（不过应该问题不大）。
3. 可以使用更好的渐变函数。

综上，明天摸鱼的时候再研究一下。

ps: 这个功能可能应该放在`set_volume`中，而不是`main_loop`

**Comment by JedSunCN** [comment]
好的，感谢感谢🙏

**Comment by lingkai5wu** [comment]
已于 16169b951e8692632b2995e70c92c1d5d99b118f 实现，感谢建议！
