### ISSUE TITLE
能否在使用其他音量合成器时使用

### ISSUE THREAD

**Issue by kakkollo** [lingkai5wu/AutoMuteBG#15]
自动静音程序只能在使用系统扬声器的情况下起到效果，在使用如SteelSeries GG中的Sonar改变音频输出时会失去作用
![屏幕截图 2024-07-13 161632](https://github.com/user-attachments/assets/3f4ccea2-de7f-4804-b290-057b6e20bf61)

**Comment by wuyilingwei** [comment]
得适配，还不知道能不能有api，估计难搞

**Comment by kakkollo** [comment]
收到

**Comment by wuyilingwei** [comment]
还有有能力可以自写（）

**Comment by kakkollo** [comment]
我不会（诚实
