### ISSUE TITLE
音量目前只会在0和100间切换

### ISSUE THREAD

**Issue by fomarara** [lingkai5wu/AutoMuteBG#4]
希望可以保持系统音量合成器的单进程音量设置，游戏内的音量无法微调

**Comment by lingkai5wu** [comment]
理解你的需求。目前正在开发的 #3 能通过修改配置文件部分实现这个功能：
![image](https://github.com/lingkai5wu/AutoMuteBG/assets/53172425/4ba02566-9746-4e81-b706-cd42758c4f1a)
fg_volume是目标进程在前台时的期望音量。例如图片中的配置，本程序会将网易云音乐的音量合成器音量调整为90%
你是想读入程序启动前音量合成器进程的音量，并把他作为fg_volume吗？

**Comment by fomarara** [comment]
> 理解你的需求。目前正在开发的 #3 能通过修改配置文件部分实现这个功能： ![image](https://user-images.githubusercontent.com/53172425/238676622-4ba02566-9746-4e81-b706-cd42758c4f1a.png) fg_volume是目标进程在前台时的期望音量。例如图片中的配置，本程序会将网易云音乐的音量合成器音量调整为90% 你是想读入程序启动前音量合成器进程的音量，并把他作为fg_volume吗？

是的，虽然手动配置也可以，但能够直接读取合成器的设置会更好用

**Comment by lingkai5wu** [comment]
好的，明天看一下是否能实现

**Comment by lingkai5wu** [comment]
简单实现了，对应[这个release](https://github.com/lingkai5wu/AutoMuteBG/releases/tag/v0.1.6) 
首次运行后会生成config.yaml，将其中的processes修改为如下形式：
```
processes:
  StarRail.exe:
    fg_volume: auto
``` 
再次运行程序应该就能看到效果了，期待你的反馈

**Comment by fomarara** [comment]
> 简单实现了，对应[这个release](https://github.com/lingkai5wu/AutoMuteBG/releases/tag/v0.1.6) 首次运行后会生成config.yaml，将其中的processes修改为如下形式：
> 
> ```
> processes:
>   StarRail.exe:
>     fg_volume: auto
> ```
> 
> 再次运行程序应该就能看到效果了，期待你的反馈

成功了，非常感谢
