### ISSUE TITLE
建议将随软件退出改成可选功能

### ISSUE THREAD

**Issue by Mr233sir** [lingkai5wu/AutoMuteBG#6]
每次开启软件需要手动开启该程序，而当软件退出时又会自动一起退出，我想将这个程序添加到开机启动列表并且永不自动退出(可手动关闭)，这样就无需手动操作了

**Comment by Mr233sir** [comment]
通过绑定一个已经开机自启的软件可以实现不自动退出，但是在该程序已经启动后打开的游戏就不会享受到这个效果，希望能改进一下

**Comment by lingkai5wu** [comment]
可以的，预计下个版本实现。
正如你说的，当前版本程序逻辑是启动时检测目标进程，因此需要加入定时检测目标进程的功能，才能在后台驻留时正常工作。
后续会在配置文件中增加驻留后台和定时检测时间间隔的配置项。
开机自启还需要研究一下。
